djangop/urls.py
from django.contrib import admin
from django.urls import path
from djangoapp import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',views.index),
    path('display/',views.display),
    path('test/',views.test),
    path('showstudents/',views.showstudents),
    path('createstudent/',views.createstudent),
    path('deleteStudent/<int:id>/',views.delete),
    path('editstudent/<int:id>/',views.edit),
    path('setsession/',views.setsession),
    path('getsession/',views.getsession),
    path('setcookie/',views.setcookie),
    path('getcookie/',views.getcookie),
    path('getpdf/',views.getpdf),
    path('getcsv/',views.getcsv),
    path('sendmail/',views.sendmail),
    path('login/',LoginView.as_view()),
    path('customreg/',views.customreg),
    path('check/',views.check),
    path('home/',views.home),
    path('logoutview/',views.logoutview),
    path('uploader/',views.uploader)
]

djangoapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    email=models.EmailField()
    date_of_Birth=models.DateField()
    age=models.IntegerField()

class UserData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    gender = models.CharField(max_length=30)
    dob = models.DateField()
    location=models.CharField(max_length=30)

djangoapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from djangoapp.models import Student
from djangoapp.form import StudentForm,TestForm,UserForm,RegForm,CustomerForm
from reportlab.pdfgen import canvas
from django.core.mail import send_mail
from djangop import settings
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from djangoapp.functions import handle_uploaded_file
import csv

# Create your views here.

def index(request):
    return HttpResponse("Welcome to Django!")

def display(request):
    return render(request,"test.html")

def test(request):
    return render(request,"test2.html")

def showstudents(request):
    students=Student.objects.all()
    return render(request,"students.html",{'students':students})

def createstudent(request): 
     if request.method=="POST": 
          form=StudentForm(request.POST) 
          if form.is_valid(): 
               form.save() 
               return redirect("/showstudents/") 
     else: 
          form=StudentForm() 
          return render(request,"createstudent.html",{'form':form}) 

def delete(request,id): 
     student=Student.objects.get(id=id) 
     student.delete() 
     return redirect("/showstudents/") 

def edit(request,id): 
     student=Student.objects.get(id=id) 
     if request.method=="POST":           
          form=StudentForm(request.POST,instance=student) 
          if form.is_valid(): 
               form.save() 
               return redirect("/showstudents/") 
     else: 
          form=StudentForm() 
     return render(request,"editstudent.html",{'form':form,'student':student}) 

def setsession(request):
     if request.method=="POST":
          form=TestForm(request.POST)
          if form.is_valid():
               name=request.POST['name']
               email=request.POST['email']
               request.session["name"]=name #stores name in session
               request.session["email"]=email #stores email in session
               return redirect('/getsession')
     else:
          form=TestForm()
     return render(request,'sess.html',{'form':form})

def getsession(request):
     name=request.session["name"]   #fetches session value
     email=request.session["email"] #fetches session value
     return render(request,'result.html',{'name':name,'email':email})

def setcookie(request):
     response=HttpResponse("Cookie set")
     response.set_cookie("mycookie","abcd")
     #mycookie is cookie name,abcd is cookie value
     return response

def getcookie(request):
     cookievalue=request.COOKIES["mycookie"]#fetches cookie value
     return HttpResponse("Cookie value is "+cookievalue)

def getpdf(request):
     response=HttpResponse(content_type='application/pdf')
     response['Content-Disposition']='attachment;filename="sample.pdf"'
     c=canvas.Canvas(response)
     c.setFont("Times-Roman",42)
     c.drawString(100,700,"Hello user!")
     c.showPage()
     c.save()
     return response

def getcsv(request):
     response=HttpResponse(content_type='text/csv')
     response['Content-Disposition']='attachment;filename="student.csv"'
     writer=csv.writer(response)
     writer.writerow(['Id','Name','Marks'])
     writer.writerow(['100','Kundan','90'])
     writer.writerow(['101','Rehan','92'])
     return response

def sendmail(request):
     subject = "Greetings"
     msg = "Congratulations for your success"
     to = "kundankumardec16@gmail.com"
     res = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])
     if(res == 1):
          msg = "Mail sent successfully"
     else:
          msg = "Mail could not be sent"
     return HttpResponse(msg)

def customreg(request):
     if request.method=="POST":
          user=UserForm(request.POST)
          form=RegForm(request.POST)
          if user.is_valid() and form.is_valid():
               profile = form.save(commit=False)
               profile.user = request.user
               user.save()
               profile.save()
               return redirect("/login/")
     else:
          user=UserForm()
          form=RegForm()
     return render(request,"registration/customreg.html",{'form':form,'user':user})

def check(request):
     username=request.POST['username']
     password=request.POST['password']
     user=authenticate(request,username=username,password=password)
     if user is not None:
          login(request,user)#logs in the user
          return redirect("/home")
     else:
          return redirect("/login")

@login_required
def home(request):
     username=request.user.username
     return render(request,"home.html",{'username':username})

def logoutview(request):
     logout(request)#logsout the current user
     return redirect("/login")

def uploader(request):
     if request.method=="POST":
          form=CustomerForm(request.POST,request.FILES)
          if form.is_valid():
               for f in request.FILES.getlist('file'):
                    handle_uploaded_file(f)
               #return render(request,'customer.html',{'form':form,'fi':request.FILES['file']})
               return HttpResponse('file uploaded successfully')
     else:
          c=CustomerForm()
          return render(request,'customer.html',{'form':c})

djangoapp/templates/createstudent.html
<!DOCTYPE html>
<html>
    <head>
        <title>ADD STUDENT</title>
    </head>
    <body>
        <h2 style="color: firebrick; text-align: center;">: : : : Registration for new candidates : : : :</h2>
        <form method="POST">
            {% csrf_token %}
            <table border="1px" align="center" cellpadding="10px" cellspacing="0px">
                {{ form.as_table }}
            </table><br>
            <center>
                <input type="checkbox" required> I accept the <u>Terms and Conditions</u></button><br><br>
                <button type="submit">Save</button>&nbsp;&nbsp;&nbsp;<button type="reset">Reset</button>
            </center>
        </form>
    </body>
</html>

djangoapp/templates/customer.html
<!DOCTYPE html>
<html>
    <head>
        <titile>CUSTOMER FORM</titile>
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data">
        <!--enctype indicates how the data is encoded before it reaches the server-->
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Submit</button>
        </form>
    </body>
</html>

djangoapp/templates/editstudent.html
<!DOCTYPE html> 
<html> 
    <head> 
        <title>EDIT STUDENT FORM</title> 
    </head> 
    <body> 
        <h2 style="color: firebrick; text-align: center;">: : : : Updation form : : : :</h2>
        <form method="post" action="/editstudent/{{student.id}}/"> 
        {% csrf_token  %} 
            <table border="1px" align="center" cellpadding="10px" cellspacing="0px"> 
                <tr> 
                    <th>FIRST NAME</th> 
                    <td><input type="text" name="first_name" id="id_fname" value="{{student.first_name}}"></td> 
                </tr> 
                <tr> 
                    <th>LAST NAME</th> 
                    <td><input type="text" name="last_name" id="id_lname" value="{{student.last_name}}"></td> 
                </tr> 
                <tr> 
                    <th>EMAIL</th> 
                    <td><input type="text" name="email" id="id_email" value="{{student.email}}"></td> 
                </tr> 
                <tr> 
                    <th>DATE OF BIRTH</th> 
                    <td><input type="date" name="date_of_Birth" id="id_date_of_Birth" value="{{student.date_of_Birth}}"></td> 
                </tr> 
                <tr> 
                    <th>AGE</th> 
                    <td><input type="number" name="age" id="id_age" value="{{student.age}}"></td> 
                </tr> 
            </table> <br>
            <center>
                <input type="checkbox" required> I accept the <u>Terms and Conditions</u></button><br><br>
                <button type="Submit">UPDATE</button>
            </center>
            <br><br> 
            <a href="/showstudents/">Back to List</a> 
        </form>
    </body> 
</html> 

djangoapp/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home Page</title>
    </head>
    <body>
        <h1>Hello {{username}}</h1>
        <a href="/logoutview/">Logout</a>
    </body>
</html>

djangoapp/templates/result.html
<!DOCTYPE html>
<html>
    <head>
        <title>Get Session value</title>
    </head>
    <body>
        Name is {{name}}
        Email is {{email}}
    </body>
</html>

djangoapp/templates/sess.html
<!DOCTYPE html>
<html>
    <head>
        <title>SESSION</title>
    </head>
    <body>
        <h2 style="color: firebrick; text-align: center;">: : : : Login to account : : : :</h2>
        <form method="POST">
            {% csrf_token %}
            <center>
                {{form.as_p}}
                <button type="submit">Submit</button>&nbsp;&nbsp;
                <button type="reset">Reset</button>
            </center> 
        </form>
    </body>
</html>

djangoapp/templates/students.html
<!DOCTYPE html>
<html>
    <head>
        <title>Students List</title>
        <script>
            function check()
            {
                var result=confirm("Do you really wish to delete this record");
                if(result==true)
                    return true;
                else
                    return false;
            }
        </script>
    </head>
    <body>
        <h2 style="color: darkgreen; text-align: center; text-shadow: rgb(54, 177, 177);">List of registered candidates</h2>
        <table border="1px" align="center" cellpadding="5px" cellspacing="2px">
            <tr>
                <th>FIRST NAME</th>
                <th>LAST NAME</th>
                <th>EMAIL</th>
                <th>DATE OF BIRTH</th>
                <th>AGE</th>
                <th colspan="2">ACTION</th>
            </tr>
            {% for s in students %}
            <tr>
                <td>{{s.first_name}}</td>
                <td>{{s.last_name}}</td>
                <td>{{s.email}}</td>
                <td>{{s.date_of_Birth}}</td>
                <td>{{s.age}}</td>
                <td><a href="/editstudent/{{s.id}}/">EDIT</a></td>
                <td><a href="/deleteStudent/{{s.id}}/"
                    onclick="return check()">DELETE</a></td>
            </tr>
            {% endfor %}
        </table>
        <center><a href="/createstudent/">ADD NEW STUDENT</a></center>
    </body>
</html>

djangoapp/templates/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>SAMPLE DJANGO TEMPLATE</title>
        {% load static %}
    </head>
    <body style="background-color: coral;">
        <h1 style="color: darkblue;text-align: center;">Welcome to sample template of Django</h1>
        <center><img src="{% static '/images/images1.png' %}" width='200px' height="200px" alt="No image found"></center>
        <br>
        <marquee direction="right"><a href="/test/">Go to test.html2</a></marquee>
    </body>
</html>

djangoapp/templates/test2.html
<!DOCTYPE html>
<html>
    <head>
        <title>Testing template</title>
        {% load static %}
        <link href="{% static '/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Using external stylesheet</h1>
    </body>
</html>